name: Latest Stable Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Stable version Release new apk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jam_it
      
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
      - name: Get Version Number
        id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with: 
          file-path: jam_it/pubspec.yaml
        
        
      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build apk for platfroms
        run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "jam_it/build/app/outputs/apk/release/*"
          tag: ${{ steps.read-version.outputs.version-number }}
          token: ${{ secrets.TOKEN }}

    

    
