name: Latest Stable Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jam_it
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "jam_it/build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}
    

    
