name: Latest Stable Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Stable version Release new apk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jam_it
      
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build apk for platfroms
        run: flutter build apk --release --split-per-abi

      - name: Extract version from pubspec.yaml
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo VERSION=%version% >> %GITHUB_ENV%

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "jam_it/build/app/outputs/apk/release/*"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}

    

    
